//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OredersTracker.Web.App_GlobalResources.Orders {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Order {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Order() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OredersTracker.Web.App_GlobalResources.Orders.Order", typeof(Order).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фактура в брой.
        /// </summary>
        public static string BillInCash {
            get {
                return ResourceManager.GetString("BillInCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бонуси.
        /// </summary>
        public static string Bonuses {
            get {
                return ResourceManager.GetString("Bonuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дизайнер.
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпълнена дата.
        /// </summary>
        public static string DateOfComplition {
            get {
                return ResourceManager.GetString("DateOfComplition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краен срок.
        /// </summary>
        public static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Еконт.
        /// </summary>
        public static string Econt {
            get {
                return ResourceManager.GetString("Econt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завършена.
        /// </summary>
        public static string IsComplited {
            get {
                return ResourceManager.GetString("IsComplited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доплащане.
        /// </summary>
        public static string LeftToBePaid {
            get {
                return ResourceManager.GetString("LeftToBePaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стойност на поръчката.
        /// </summary>
        public static string OrderPrice {
            get {
                return ResourceManager.GetString("OrderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платено на.
        /// </summary>
        public static string PaidAt {
            get {
                return ResourceManager.GetString("PaidAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фактура по банка.
        /// </summary>
        public static string PaidBankTransaction {
            get {
                return ResourceManager.GetString("PaidBankTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аванс.
        /// </summary>
        public static string PaidInAdvance {
            get {
                return ResourceManager.GetString("PaidInAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В брой без документ.
        /// </summary>
        public static string PaidInCashWithouotReceipt {
            get {
                return ResourceManager.GetString("PaidInCashWithouotReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платено с карта.
        /// </summary>
        public static string PaidWithCard {
            get {
                return ResourceManager.GetString("PaidWithCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Касова бележка.
        /// </summary>
        public static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }
    }
}
